"""initial schema

Revision ID: 2df4d07299c8
Revises: 
Create Date: 2026-07-01 16:10:26.225274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2df4d07299c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_chips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_about_chips_order_index'), 'about_chips', ['order_index'], unique=False)
    op.create_table('about_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('history', sa.Text(), nullable=True),
    sa.Column('mission', sa.Text(), nullable=True),
    sa.Column('vision', sa.Text(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('image1', sa.String(length=1024), nullable=True),
    sa.Column('image2', sa.String(length=1024), nullable=True),
    sa.Column('image3', sa.String(length=1024), nullable=True),
    sa.Column('image4', sa.String(length=1024), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('about_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_about_stats_order_index'), 'about_stats', ['order_index'], unique=False)
    op.create_table('admins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_table('client_logos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('logo_url', sa.String(length=1024), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_logos_order_index'), 'client_logos', ['order_index'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_order_index'), 'clients', ['order_index'], unique=False)
    op.create_table('clients_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intro_text', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_info_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('hours', sa.String(length=255), nullable=False),
    sa.Column('whatsapp', sa.String(length=64), nullable=False),
    sa.Column('instagram_url', sa.String(length=1024), nullable=True),
    sa.Column('youtube_url', sa.String(length=1024), nullable=True),
    sa.Column('linkedin_url', sa.String(length=1024), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('service', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('notified_studio', sa.Boolean(), nullable=False),
    sa.Column('notified_visitor', sa.Boolean(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gallery_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('src', sa.String(length=1024), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_items_order_index'), 'gallery_items', ['order_index'], unique=False)
    op.create_table('hero_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hero_images_order_index'), 'hero_images', ['order_index'], unique=False)
    op.create_table('hero_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page_heroes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('page_key', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=1024), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_heroes_page_key'), 'page_heroes', ['page_key'], unique=True)
    op.create_table('services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=1024), nullable=True),
    sa.Column('extended_description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_order_index'), 'services', ['order_index'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('photo', sa.String(length=1024), nullable=True),
    sa.Column('position', sa.String(length=32), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_members_order_index'), 'team_members', ['order_index'], unique=False)
    op.create_table('testimonials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('logo_src', sa.String(length=1024), nullable=True),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_testimonials_order_index'), 'testimonials', ['order_index'], unique=False)
    op.create_table('visit_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_backups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otp_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_codes_admin_id'), 'otp_codes', ['admin_id'], unique=False)
    op.create_table('portfolio_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('image', sa.String(length=1024), nullable=True),
    sa.Column('video_url', sa.String(length=1024), nullable=True),
    sa.Column('bts_url', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=1024), nullable=True),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_items_order_index'), 'portfolio_items', ['order_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_items_order_index'), table_name='portfolio_items')
    op.drop_table('portfolio_items')
    op.drop_index(op.f('ix_otp_codes_admin_id'), table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_table('content_backups')
    op.drop_table('visit_counter')
    op.drop_index(op.f('ix_testimonials_order_index'), table_name='testimonials')
    op.drop_table('testimonials')
    op.drop_index(op.f('ix_team_members_order_index'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_services_order_index'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_page_heroes_page_key'), table_name='page_heroes')
    op.drop_table('page_heroes')
    op.drop_table('hero_settings')
    op.drop_index(op.f('ix_hero_images_order_index'), table_name='hero_images')
    op.drop_table('hero_images')
    op.drop_index(op.f('ix_gallery_items_order_index'), table_name='gallery_items')
    op.drop_table('gallery_items')
    op.drop_table('contact_messages')
    op.drop_table('contact_info_settings')
    op.drop_table('clients_settings')
    op.drop_index(op.f('ix_clients_order_index'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_client_logos_order_index'), table_name='client_logos')
    op.drop_table('client_logos')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    op.drop_index(op.f('ix_about_stats_order_index'), table_name='about_stats')
    op.drop_table('about_stats')
    op.drop_table('about_settings')
    op.drop_index(op.f('ix_about_chips_order_index'), table_name='about_chips')
    op.drop_table('about_chips')
    # ### end Alembic commands ###
