"""add admin avatar_url

Revision ID: c9e5c6644b35
Revises: 60ab14ecbfb1
Create Date: 2026-07-10 12:37:54.107731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9e5c6644b35'
down_revision: Union[str, Sequence[str], None] = '60ab14ecbfb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('avatar_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'avatar_url')
    # ### end Alembic commands ###
